name: SolarMind
version: "1.0.3-beta"
slug: solarmind
description: SolarMind photovoltaic analysis engine
url: "https://github.com/Aurelniv/SolarMind-Addon"
arch:
  - amd64
  - aarch64
  - armv7
startup: services
boot: auto
init: false
homeassistant_api: true
hassio_api: true
mqtt: true
options:
  mqtt_host: core-mosquitto
  mqtt_port: 1883
  mqtt_username: "ha-mqtt"
  mqtt_password: "9jjiVawEV5ZjvV8"
schema:
  mqtt_host: str
  mqtt_port: int
  mqtt_username: str
  mqtt_password: password
